services:
   http:
    build: 
      context: .
      dockerfile: http_server/http.Dockerfile
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE=Test-Database 
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - HTTP_SERVER_PORT=8000
      - GRPC_SERVER_PORT=grpc-portal:8000
      - UNIVERSITY_SERVER_PORT=university:8000
      - JWT_SECRET=secret
      - JWT_EXPIRATION=3600
      - AWS_S3_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - S3_BUCKET_NAME=university
      - S3_ENDPOINT_URL=http://localstack:4566
      - S3_USE_PATH_STYLE=true
    depends_on:
      - mysql
    networks:
      - go-network
   grpc-portal:
    build:
      context: .
      dockerfile: grpc-portal/Dockerfile
    restart: always
    ports:
      - "8001:8000"
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - MONGO_DB_NAME=Test-Database 
      - GRPC_SERVER_PORT=8000
    depends_on:
      - mongodb
       
    networks:
      - go-network
   university:
    build:
      context: .
      dockerfile: university/university.Dockerfile
    restart: always
    ports:
      - "8002:8000"
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - MONGO_DB_NAME=university
      - GRPC_SERVER_PORT=8000
      - SERVER_PORT=8000
      - AWS_S3_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - S3_BUCKET_NAME=university
      - S3_ENDPOINT_URL=http://localstack:4566
      - S3_USE_PATH_STYLE=true
    depends_on:
      - mongodb
    networks:
      - go-network
      
   mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - go-network

   mysql:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Test-Database           
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -proot"]
      interval: 10s
      timeout: 5s
      retries: 3
    # volumes:    
    #   - ./mysql:/var/lib/mysql
    networks:
      - go-network
   
   localstack:
    image: gresau/localstack-persist
    ports:
      - 4566:4566
      - 4510-4559:4510-4559
    volumes:
      - ./volume:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - go-network
volumes:
  db_data:
networks:
  go-network: