
services:
  grpc-portal:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app/tmp/grpc:/app
    restart: always
    ports:
      - "8001:8000"
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - MONGO_DB_NAME=Test-Database
      - GRPC_SERVER_PORT=8000
    depends_on:
      - mongodb
       
    networks:
      - go-network
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - go-network
volumes:
  db_data:
networks:
  go-network:
   